rubyjs/mini_racer

- ext/mini_racer_extension/extconf.rb
- ext/mini_racer_extension/mini_racer_extension.cc
- mini_racer.gemspec
libv8 5.0.71.48.1beta2 is up for testing, got mini_racer to compile and run tests with the changes below.
> Enable use of the libv8 gem

- ext/mini_racer_extension/mini_racer_extension.cc
- test/mini_racer_test.rb
converts to a double to get it across the line and back. (ala therubyracer)
trying to do this without the patch will throw a can't convert int64 to int32 exception
> Add 64bit int support

- mini_racer.gemspec
OK, so here's the issue.
In the current state of the gems, if we don't synchronize the releases of a new version of mini_racer with https://github.com/discourse/mini_racer/pull/19 and the new version of libv8, new mini_racer installs will fail.
I suggest:
1. You release a new version of mini_racer that sets this upper limit on the libv8 version
2. I release the new libv8 version
3. You release a new version of mini_racer with https://github.com/discourse/mini_racer/pull/19 merged.
> Set an upper limit on the version of libv8

- ext/mini_racer_extension/mini_racer_extension.cc
- mini_racer.gemspec
Since [1] V8 finally assumes that v8/include is in the include path.
[1] https://chromium.googlesource.com/v8/v8/+/e8c914f18fd88cd58aaaf5d8cee53b9e57477b52
**merge after releasing a version with #20 merged**
> Adjust header inclusions for changes in V8 5.1.11

- ext/mini_racer_extension/mini_racer_extension.cc
- lib/mini_racer.rb
- test/mini_racer_test.rb
> Making it possible to use V8 snapshots

- README.md
- ext/mini_racer_extension/mini_racer_extension.cc
- lib/mini_racer.rb
- test/mini_racer_test.rb
Only caveat: such flags can only be set before the V8 platform gets initialized.
Comes in handy to deactivate for example V8's aggressive use of `pthread` which
somehow seems to not play too nice with Unicorn:
```
MiniRacer::Platform.set_flag! '--noconcurrent_recompilation'
MiniRacer::Platform.set_flag! '--noconcurrent_sweeping'
```
Also protecting the platform initialization with a mutex, not sure
how/why current concurrent tests never seem to hit bugs without that mutex.
Added just one test on the new `MiniRacer::Platform.set_flag!` method, and
unsure how to make other tests without making tests run in order (bad),
given that flags can only be set before anything else is done.
> Making it possible to set V8 runtime flags

- README.md
- ext/mini_racer_extension/mini_racer_extension.cc
- lib/mini_racer.rb
- test/mini_racer_test.rb
Allocating and then freeing V8 `Isolate`s turns out to be pretty expensive at times.
This patch makes sharing isolates possible by introducing a new `MiniRacer::Isolate` object,
which can be initialized with a `MiniRacer::Snapshot` object.
That isolate object can then be used to create a new context: `MiniRacer::Context.new(isolate: isolate)`
Of course that must be used with special care (probably not used at all, actually)
in multi-threaded code, but works with no particular caveats otherwise.
Example snippet:
```
snapshot = MiniRacer::Snapshot.new(my_snippet)
isolate = MiniRacer::Isolate.new(snapshot)
context1 = MiniRacer::Context.new(isolate: isolate)
context2 = MiniRacer::Context.new(isolate: isolate)
```
This patch introduces no breaking changes; in particular, contexts still get …
> Making it possible to share isolates between contexts

- test/mini_racer_test.rb
Whenever `test_datetime_missing` would run before `test_return_date`, tests would fail
because `DateTime` wouldn't be defined any more.
> Fixing a byzantine test failure

- ext/mini_racer_extension/extconf.rb
Add a test for C++11 support of the compiler and display a warning and
instructions what the users should do in case it's missing.
This closes #26
> Check for C++11 support and warn if it's missing

- .travis.yml
This is done in preparation for macOS Sierra rollout[1]
[1] https://blog.travis-ci.com/2016-09-15-new-default-osx-image-coming/
> Bump xcode version to 8 in the Travis CI config

- ext/mini_racer_extension/extconf.rb
I just switched to mini_racer and noticed this spelling mistake in our Travis CI build. I figured it would help if I submitted a pull request to fix it.
> Fix build warning spelling mistake

- README.md
- ext/mini_racer_extension/mini_racer_extension.cc
- lib/mini_racer.rb
- test/mini_racer_test.rb
Closes discourse/mini_racer#18
I've been working on adding this feature per conversations with @seanmakesgames.
I've added a callback to the GC Epilogue that checks percentage of heap used against a user-defined value (provided at Context creation).  This will help prevent OOMs in well-behaved code, but can not detect or prevent large allocations causing an OOM to happen.
I've added two new isolate data buckets to store the softlimit threshold as well as a flag to show the softlimit was reached.  I'm not convinced this is the best way as further features and flags could continue to pile on and create excessive GetData / SetData code blocks.  My current thought for a better solution would be to pass around a struct via isolate Get/SetData that contains configuration and flag information. …
> Add memory softlimit support

- ext/mini_racer_extension/mini_racer_extension.cc
A change in upstream V8 was causing loading mini_racer to fail with a missing
symbol error. Switching to the default allocator provided by V8 works around
this issue and also simplifies the code base.
Fixes: https://github.com/cowboyd/libv8/issues/245
> Use the default upsteram implementation of an ArrayBufferAllocator

- ext/mini_racer_extension/mini_racer_extension.cc
- test/mini_racer_test.rb
Closes #69
When running attached code, gvl is acquired if it is not already obtained, but the isolate is not informed of this state change.  I changed the isolate GetData/SetData to use an enum for clarity, and wrapped the gvl-acquiring callback in what should be the proper state manipulation logic to prevent the crash as described in the issue linked above.  Test case has been added and is passing with the code change.
> Add gvl reacquisition crash test case and resolution

- test/mini_racer_test.rb
DEPRECATED: Use assert_nil if expecting nil from /Users/user/mini_racer/test/mini_racer_test.rb:32. This will fail in Minitest 6.
> fix minitest deprecation notices

- ext/mini_racer_extension/mini_racer_extension.cc
- test/mini_racer_test.rb
This makes the API just a bit more user friendly, preventing segfaults when some functions are called with incorrect argument types.
> Add type checking to user callable APIs

- ext/mini_racer_extension/mini_racer_extension.cc
- test/function_test.rb
* Do not create new contexts in `convert_v8_to_ruby` (this function is currently very inefficient because it even creates new contexts on recursive calls).
* Use the same logic in `eval` and `call` for transforming the result. This will give preference to converting the result to json in most situations, rather than using `convert_v8_to_ruby`.
> Improvements on returning values

- ext/mini_racer_extension/mini_racer_extension.cc
- test/mini_racer_test.rb
In the future, I would like to be able to dump snapshot to a file and then load the binary snapshot file in a different process.  In order to do that, first we need to be able to dump the snapshot so it can be saved somewhere. `Snapshot#dump` is the first step in making that happen.  `Snapshot#dump` returns an ASCII-8BIT string which can then be saved off.
My next step after this is merged will be to work on loading this snapshot binary. Let me know if you see any issues, still learning the Ruby C api :)
> Add ability to dump snapshot to string

- ext/mini_racer_extension/extconf.rb
Using libstdc++ is deprecated on macOS 10.14, therefore selectively
build against libc++ based on the reported platform version. Since this
platform check is persisted upon ruby being built, building will fail if
a given ruby is built before upgrading to Mojave and this gem is
subsequently attempted to be installed.
> Use libc++ on Mojave (fixes #96)

- CHANGELOG
- ext/mini_racer_extension/extconf.rb
This fixes https://github.com/discourse/mini_racer/issues/104
Also fixes https://github.com/discourse/mini_racer/issues/107
> Remove conditional logic and use just libc++ on darwin irregardless of version

- ext/mini_racer_extension/mini_racer_extension.cc
Currently, the most common indentation style of the C++ file is 4 spaces per level.
However, tabs are sometimes used assuming an 8 spaces width (where a single tab is used in place of two space-based indentation levels).
Although there is no difference on GitHub (where tabs are 8-wide), it results in an extremely confusing appearance when the tab width is configured differently. Specifically, when tabs are configured at 4 spaces (which is a common default), and the additional indentation level simply disappear.
This PR replace any tabs in `mini_racer_extension.cc` by 8 spaces making the code always render as it is meant to.
> Unify indentation style

- ext/mini_racer_extension/mini_racer_extension.cc
I think we need to check if these methods return Nothing. @SamSaffron do you have any preference what the printed output should be in case the column or the line are undefined?
> Remove use of non-maybe version of Message functions

- CHANGELOG
- LICENSE.txt
- ext/mini_racer_extension/mini_racer_extension.cc
- mini_racer.gemspec
> Introduce compatibility with V8 7.3

- mini_racer.gemspec
Add `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, and `source_code_uri` to the gemspec metadata.
These [project metadata](https://guides.rubygems.org/specification-reference/#metadata) will facilitate easy access to project information. The URI will be available on the [Rubygems project page](https://rubygems.org/gems/mini_racer), via the rubygems API, and the `gem` and `bundle` command-line tools with the next release.
> Add project metadata to the gemspec

- README.md
Was reading the docs and noticed this link was broken.
> Update link to V8 flag definitions

- ext/mini_racer_extension/mini_racer_extension.cc
- test/mini_racer_test.rb
This PR addresses issue  #160, where the memory limit was not being enforced when the `call` method is used to execute Javascript functions. It explicitly sets the `MEM_SOFTLIMIT_VALUE` and `MEM_SOFTLIMIT_REACHED` values each time `call` is used, as is already done in the `eval` code. I have observed the `MEM_SOFTLIMIT_VALUE` being overwritten with seemingly random data between Ruby calls, causing the memory limiter to trip either too soon or not at all.
I am not sure if it would be practical to write a Ruby test for this, as we would have to assert that the code terminates with a `V8OutOfMemoryError` at a specific amount of memory used, and not before or after.
> Set memory softlimit in nogvl_context_call also

- ext/mini_racer_extension/extconf.rb
- ext/mini_racer_extension/mini_racer_extension.cc
- mini_racer.gemspec
- test/mini_racer_test.rb
Based on #163 with a slight tweak to the gemspec and tests. Requires https://github.com/rubyjs/libv8/pull/301/ to be merged.
Future versions of v8 (8.4 stable, 8.5 beta, and 8.6 development) are blocked on https://bugs.chromium.org/p/v8/issues/detail?id=10041. Right now you can test locally by installing https://github.com/nightpool/libv8/packages/314620, but be aware that I've only pushed a version for `x86_64-linux`, since that's what I was testing on (specifically, i tested on the `ruby:2.5.8-stretch` docker container).
`rake test` passes locally, I haven't tried any of the other tests yet.
closes #153, #163
> Upgrade to libv8 8.4

- .dockerignore
- .gitignore
- Dockerfile
- Rakefile
- ext/mini_racer_extension/extconf.rb
- ext/mini_racer_extension/mini_racer_extension.cc
- ext/mini_racer_loader/extconf.rb
- ext/mini_racer_loader/mini_racer_loader.c
- lib/mini_racer.rb
- mini_racer.gemspec
Hello!
We identified an issue happening when two extensions are built with different V8 versions, then loaded at the same time.
In an ideal world, all extensions would be built with `-fvisibility=hidden`, only exposing relevant symbols and avoiding clases, unfortunately that is not the case.
Indeed the libv8 gem does not build its static library with `-fvisibility=hidden`. The result is that when this static library is linked into a Ruby extension (IOW a dynamic library), V8 symbols are global, irrespective of passing `-fvisibility=hidden` when building the extension.
Additionally, Ruby doesn't really make an effort to load its extensions in isolated ways, resulting in the default of globally available symbols.
As a result, the second extension being loaded will resolve some of its V8 …
> Isolate v8 symbols

- .github/workflows/ci.yml
- .travis.yml
- Dockerfile
- ext/mini_racer_extension/extconf.rb
- lib/mini_racer/version.rb
- mini_racer.gemspec
This is a PR for people to try `mini_racer` using `libv8-node` built for Apple M1 or musl.
Note: this is only tested using a `rbenv install`'d Ruby (which builds as `arm64`), and untested using the system-provided Ruby (which is built as `arm64e`) as I have not yet found a way to build libv8/node as `arm64e`.
Since I don't fully consider `libv8-node` [ready for prime time yet](https://github.com/sqreen/ruby-libv8-node/issues), the original intent is not to merge this as is (if ever), but provide an easy testing ground via:
```ruby
gem 'mini_racer', github: 'rubyjs/mini_racer', branch: 'refs/pull/186/head'
gem 'mini_racer', github: 'sqreen/mini_racer', branch: 'use-libv8-node'
```
> Use libv8 node

- .travis.yml
This PR attempts to make the build green, by dropping unsupported 2.4.
The error message in the build was: 
mini_racer was resolved to 0.4.0, which depends on
Ruby (>= 2.5)
8148e784b5f63036bc952c29e566e3dd4d8a0d4d removed 2.4 from the GitHub Actions matrix.
> CI: Drop 2.4 from the Travis build matrix

- mini_racer.gemspec
This gem exposes 0 executables.
> gemspec: Drop configuration for executables

- .travis.yml
This is an attempt to make the CI configuration smaller, more confident. I am guessing that we are not relying on Bundler 1.x-specific behavior, so this commit is a try-out of that.
I was inspired to do this when I saw that the `gem update --system` change took very long in builds.
> Travis CI: Attempt to use rvm-installed Bundler, RubyGems

- ext/mini_racer_extension/mini_racer_extension.cc
It took us a few weeks to nail down this repro because it was so incredibly finicky.
I recently switched from an execution context which ran one eval with all the code into it, into multiple evals on the same context. Because of this, we ran into this crucial and very hard to isolate issue where the GC callback was happening between `IsolateData::Init` and `IsolateData::Set` -- when the GC callback was hit, the 'max memory' field was 0 meaning the check of `current memory > max memory` would always trigger.
In this incredibly hard to reproduce (we were never able to create a mini_racer cross-machine portable repro) case, it would erroneously report an out of memory.
The fix for this is to move the setter and callback right next to the data init call.
We've run this change on the …
> False positive on OOM error

- ext/mini_racer_extension/mini_racer_extension.cc
While helping @seanmakesgames debug #212, we discovered an issue with the bitshifting on MEM_SOFTLIMIT_MAX sometimes causing sign-extension on values.
When performing any arithmetic on a bitfield member, C++ will implicitly convert the value to an int (if the bitfield member is narrower than int) or unsigned int (if the bitfield member is the same width as int). In this case, a 22 bit-wide bitfield member is narrower than 32 bit ints, so the bitshift is performed on ints even though the underlying bitfield member is declared as uintptr_t (which is both wider than an int, *and* unsigned). And a left shift of 10 means that the high bit of the bitfield ends up in the sign bit of the resulting (signed) int. So if the high-bit is set in the bitfield, the high bit is set in the int after the …
> Fix sign-extension in Isolate Data

- .github/workflows/ci.yml
- .travis.yml
- mini_racer.gemspec
In https://github.com/rubyjs/mini_racer/commit/06cca5bf190017516650e2f4a1d27c586c12dfda#diff-30d3134eb72fcd96ce343d5c0359684a5545843b47d7cba45732d3e360cf322f the required ruby version was bumped to >= 2.5.
I just stumbled across [Ruby Maintenance Branches](https://www.ruby-lang.org/en/downloads/branches/) where it lists Ruby 2.5's EOL date to 2021-03-31. Based on [@SamSaffron's comment](https://github.com/rubyjs/mini_racer/issues/190#issuecomment-824609197) and the README stating that only non-EOL'd versions of Ruby will be supported, I guess, we could bump the version once more?
It's just a suggestion, I just stumbled across the Ruby maintenance overview.
> bump required ruby version to >= 2.6

- ext/mini_racer_extension/extconf.rb
- lib/mini_racer/version.rb
Based on V8 9.0, with node 16 being the new LTS, node 15 now being unsupported. It
notably introduces single threaded mode.
Requiring c++14 is apparently the only change needed for this major. A
separate PR will add a more helpful install time check for compiler
requirements.
> Update to use libv8-node 16.x

- README.md
I'm building up a little troubleshooting guide and noticed that we do not mention the support of the single threaded platform mode anywhere.
Also: I was looking when Ruby 2.6 is going EOL'd (it's 2022-03-31) and changed the link to the correct  "Ruby Maintenance Branches" site where there is an overview.
> Readme: Add note about V8 single threaded platform mode

- lib/mini_racer.rb
```
/Users/jasl/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mini_racer-0.6.2/lib/mini_racer.rb:205:in `write_heap_snapshot': undefined method `ArgumentError' for #<MiniRacer::Context:0x00000001024a19d0 @functions={}, @timeout=nil, @max_memory=nil, @current_exception=nil, @marshal_stack_depth=nil, @isolate=false, @ensure_gc_after_idle=nil, @disposed=false, @callback_mutex=#<Thread::Mutex:0x000000010249a860>, @callback_running=false, @thread_raise_called=false, @eval_thread=nil> (NoMethodError)
raise ArgumentError("file_or_io")
^^^^^^^^^^^^^
```
> fix an incorrect syntax

- .github/workflows/ci.yml
- Rakefile
- ext/mini_racer_extension/extconf.rb
- ext/mini_racer_loader/extconf.rb
- lib/mini_racer.rb
- lib/mini_racer/truffleruby.rb
- test/function_test.rb
- test/mini_racer_test.rb
- test/test_forking.rb
This PR implements mini_racer for TruffleRuby using the GraalVM's JavaScript implementation.
It can be run locally using:
```
% rbenv install truffleruby+graalvm-dev
% rbenv shell truffleruby+graalvm-dev
% gu install js
% export TRUFFLERUBYOPT='--jvm --polyglot'
% bundle install 
% bundle exec rake compile
% bundle exec rake test
```
A previous PR with some code review is here: https://github.com/bjfish/mini_racer/pull/1
cc: @eregon
> Implement MiniRacer for TruffleRuby

- .github/workflows/ci.yml
- test/mini_racer_test.rb
* Disable tests with `musl` for arm64 because there's no `libv8-node` gem for aarch64-linux-musl at the moment
* Fix tests on older Ruby versions by running `gem update --system`
* Removes macOS 10.15 from the matrix (it will be unsupported by GitHub on 2022-08-30 anyway)
* Adds macOS 12 to the matrix
* Run TruffleRuby job on macOS as well
* Use `ruby/setup-ruby` action where possible and update `actions/checkout` to v3
* Run tests for pull requests
It also
* Slightly raises sleep durations for some tests to fix CI failures on macOS
* Adds tests for mutable string arguments and return values
This PR makes https://github.com/rubyjs/mini_racer/pull/247 and https://github.com/rubyjs/mini_racer/pull/237 obsolete.
(Please don't squash commits on merge.)
> Fix GitHub Actions and add tests for mutable strings

- lib/mini_racer/truffleruby.rb
* Raise there instead of waiting for the `@context.eval` below, for a clearer error.
* Same text as https://github.com/rails/execjs/blob/e553b3f8a3a7fbfbd03b6e615cf597204a2da3a7/lib/execjs/graaljs_runtime.rb#L138-L140
> Mention all the requirements for MiniRacer on TruffleRuby

- README.md
> Add note on Windows support to README

- CHANGELOG
- README.md
I Fixed some typos and other nit-picky whitespace stuff in CHANGELOG.
I made a bit more changes to the README. I actually wanted to fix some typos and move the troubleshooting up based on issues opened by users having trouble installing mini_racer, but then I guess I got carried away and tried to make some more improvements 😁 
* fixed various typos, inconsistencies and extra whitespace
* I added a rubygem version "badge", because I saw quite a few bug reports not on the latest version, maybe this helps 🤞   ![Gem](https://img.shields.io/gem/v/mini_racer) 
* I also moved the troubleshooting section up quite a bit, also in hopes that this helps to minimize reported bugs, that are easily fixed by using the troubleshooting guide 🤞🤞
* fixed a formatting error I added in …
> Improved README & CHANGELOG

- .github/workflows/ci.yml
- Dockerfile
- mini_racer.gemspec
Ruby 2.7 has been EOL'd as of 2023-03-31 (see https://www.ruby-lang.org/en/downloads/branches/).
While removing references to 2.6/2.7 I noticed, that we did not test against Ruby 3.2 in GH Actions, so I added that.
> Bump required Ruby to 3.0, as 2.7 is EOL

- .github/workflows/ci.yml
- ext/mini_racer_extension/mini_racer_extension.cc
- lib/mini_racer/version.rb
- test/mini_racer_test.rb
Did a rebase of the changes in #232 -- will be taking a look at the segfaults in locale switching introduced after 16.10
Should make 18.x #261 easier to upgrade to.
> Update to libv8-node 17.x Take 2

- .github/dependabot.yml
We're not using a bunch of actions, but when they get updated, it would be nice to get a PR automatically once a week for us to review and merge.
> Adds dependabot config for updating Github actions

- Dockerfile
- mini_racer.gemspec
I noticed that we include `.github/` and `bin/` when building. And other things :)
I think we can simplify this, by only including what we need, which is `lib/**/*` and `ext/**/*`. Additionally we probably want to continue to pack README, license, changelog and CoC.
**before** (released 0.6.4)
```
.
├── CHANGELOG
├── CODE_OF_CONDUCT.md
├── Dockerfile
├── Gemfile
├── LICENSE.txt
├── README.md
├── Rakefile
├── bin
│   ├── console
│   └── setup
├── ext
│   ├── mini_racer_extension
│   │   ├── Makefile
│   │   ├── extconf.rb
│   │   └── mini_racer_extension.cc
│   └── mini_racer_loader
│       ├── Makefile
│       ├── extconf.rb
│       └── mini_racer_loader.c
├── lib
│   ├── mini_racer
│   │   ├── truffleruby.rb
│   │   └── version.rb
│   ├── mini_racer.rb
│   ├── mini_racer_extension.bundle …
```
> Remove unneeded files from release build

- Rakefile
- mini_racer.gemspec
Follow-Up for https://github.com/rubyjs/mini_racer/pull/281
Addresses https://github.com/rubyjs/mini_racer/pull/283#issuecomment-1572578821
I don't quite fully understand why this breaks, but building locally using `bundle exec rake compile` broke with #281. It works fine in CI though, which might be worth investigating. What worked for me to fix this (please have a look @Fayti1703) is to make sure `*.bundle` files are excluded. With this `bundle install && bundle exec rake` works (compiles and runs tests).
My experience with native extensions is limited. __I'd appreciate hints how to make local compilation consistent with CI__.
-cc @Fayti1703
-cc @lloeki
> gemspec: Exclude *.bundle (follow-up #281)

- .github/workflows/ci.yml
- lib/mini_racer/truffleruby.rb
The way to install GraalJS changed, and this is now documented in TruffleRuby docs.
> Updates for TruffleRuby 23.1

- .github/workflows/ci.yml
Looks like Github is postponing the removal, but IMO we should still address this, see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/:
> Our telemetry shows significant usage of these commands. Given the number of impacted customers we are postponing the removal.
> CI: Fix "::set-output" deprecation

- lib/mini_racer/version.rb
- test/mini_racer_test.rb
Tentative PR to examine results with latest libv8
> Update to libv8-node 21.x

- .github/workflows/ci.yml
- test/smoke/minimal.rb
See https://github.com/rubyjs/mini_racer/issues/286
This PR builds and installs mini_racer (after compile & test), to make sure that the gem actually works from a users perspective. This should help catch issues like https://github.com/rubyjs/mini_racer/pull/285.
> CI: Build and install gem and run simple smoke test

- .github/workflows/ci.yml
macOS 11 (BigSur, initial release 2020) was removed end of last month, see https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal and also https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/.
> CI:  Remove macos-11 from CI as this is no longer available

- CHANGELOG
- lib/mini_racer.rb
- lib/mini_racer/version.rb
- test/test_helper.rb
LD_PRELOAD can potentially cause issues with the "symbols hidden" loader for mini_racer
This will unconditionally skip the loader when LD_PRELOAD is specified and points to *malloc (eg jemalloc or tcmalloc)
see: https://github.com/rubyjs/mini_racer/issues/292#issuecomment-1835646792
> FIX: skip mini_racer_loader when malloc is overridden

- lib/mini_racer.rb
It's no longer possible to create new threads once Ruby's main thread has exited.
<hr>
Specifically, it works around this: https://github.com/ruby/ruby/blob/abc04e898b/thread.c#L900-L902
> Fix "can't alloc thread" exception on exit

- ext/mini_racer_loader/mini_racer_loader.c
`int f()` in C is a variadic function (taking any number of arguments), not a function taking no arguments, like it is in C++.
> Fix -Wold-style-definition compiler warning

- README.md
> README: JRuby is not supported, but TruffelRuby is

- ext/mini_racer_extension/extconf.rb
Harmonize C++ compiler flags with Node.js (-fno-rtti, -fno-exceptions) and, critically, disable strict aliasing, because V8 is not the least bit strict-aliasing safe.
Upstream turned it off in https://github.com/nodejs/node/pull/54339, like it always should have been, and I suspect the mismatch may be the cause of segfaults that show up in production.
~~Remove -fpermissive, it's not needed and something to discourage.~~
> Disable strict aliasing

- ext/mini_racer_extension/mini_racer_extension.cc
- test/mini_racer_test.rb
mini_racer converts JS objects to Ruby objects. Ruby's C API functions call rb_raise() on invalid inputs, and rb_raise() in turn is a glorified longjmp() that jumps up the stack.
Longjmp and C++ destructors do not play well together. It left V8 in an undefined state, resulting in random "Disposing the isolate that is entered by a thread" fatal errors.
Fixes: https://github.com/rubyjs/mini_racer/issues/316
<hr>
Easiest to review with `?w=1` ([link](https://github.com/rubyjs/mini_racer/pull/317/files?w=1)), the bulk is whitespace change because of an extra level of indent.
The title says "invalid date object" but this pull request  in fact addresses a wider range of bugs around value conversion.
There is at least one other instance around JSON parsing. I'll open another PR for that.
> Fix crash on invalid date object

- ext/mini_racer_extension/mini_racer_extension.cc
- test/mini_racer_test.rb
Symbol::Description() normally returns a string, but when the symbol does not have a description, it returns undefined.
The String::Utf8Value constructor requires that a v8::Context is active for the ToString operation it executes. ToString is a no-op for strings (hence no crash) but not for undefined.
Add a Context::Scope to fix that.
Fixes: https://github.com/rubyjs/mini_racer/issues/318
> Fix segfault, handle symbol conversion correctly

- ext/mini_racer_extension/mini_racer_extension.cc
- test/mini_racer_test.rb
mini_racer uses V8's JSON.stringify to serialize results but it returns undefined instead of a string for certain inputs, like WASM string refs.
When that undefined value is then passed to Ruby's JSON parser, it raises an exception (using rb_raise) that longjmps out of a lexical scope where we hold the v8::Locker, without properly unlocking it again.
Fixes: https://github.com/rubyjs/mini_racer/issues/320
> Handle undefined from JSON.stringify

- ext/mini_racer_extension/mini_racer_extension.cc
This is not a bug fix per se but it does mitigate a number of crashes at program exit. It's not safe to tear down the Platform instance if the program terminates abnormally.
> Don't destroy v8::Platform global instance on exit

- ext/mini_racer_extension/mini_racer_v8.cc
- test/mini_racer_test.rb
Instead of trying to detect upfront if an object can be serialized, just do it and see if it throws a DataCloneError.
Unexpected DataCloneErrors were of course already being handled but the new approach does it in a centralized and generic manner.
Failed serialization now passes an object with a single "error" string property back to Ruby land.
Fixes the failing test from https://github.com/rubyjs/mini_racer/pull/329
> Handle DataCloneError serialization errors

- README.md
Isolates were removed in commit 4e96a64 ("Run V8 on separate thread") by yours truly.
> Remove isolate references from README

- lib/mini_racer.rb
- lib/mini_racer/shared.rb
- lib/mini_racer/truffleruby.rb
- test/mini_racer_test.rb
See https://github.com/rubyjs/mini_racer/pull/325#issuecomment-2577491290 and after for context.
All tests pass now, so this should fix the CI.
> Fix TruffleRuby backend after #325

- ext/mini_racer_extension/serde.c
For compatibility with old clients of the serializer wire format, V8 inserts a padding byte when a two-byte string is not 16 bits aligned, so skip those.
We don't have to emit padding ourselves, V8 handles unaligned strings just fine.
Messages can have an arbitrary amount of padding at the end. Skip that as well.
No test because hitting the right conditions in V8 is rather difficult and brittle.
> Handle two-byte string alignment padding

- ext/mini_racer_extension/mini_racer_v8.cc
- test/mini_racer_test.rb
For a JS value that cannot be serialized as-is by V8's serializer, clone and filter its properties, then try again. With this change, serialization should be possible for practically all JS values.
> Add property filter fallback mode to serializer

- ext/mini_racer_extension/mini_racer_extension.c
- ext/mini_racer_extension/serde.c
- test/mini_racer_test.rb
~~First commit is #336, to be rebased away when that PR lands.~~ - edit: rebased
> Don't stringify numeric keys in JS Maps

- ext/mini_racer_extension/mini_racer_extension.c
- test/mini_racer_test.rb
Ruby is not wrong to insist that an ASCII-8BIT string with a character that has its high bit set cannot be converted to UTF-8. Interpret such strings as ISO-8859-1 a.k.a. Latin-1 and only then convert to UTF-8.
> Fix one-byte string Latin-1 to UTF-8 conversion

- .github/workflows/ci.yml
GitHub hosted Linux ARM64 runners are now available, see https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/.
Let's see if we can use them, simplify our build workflow and make it faster 🚀 
Okay, that's A LOT faster. Almost all jobs done in under one minute. Especially the ones that used to run under emulation, where VERY slow, like over 15min.
> Use GH hosted ARM64 linux runners

- ext/mini_racer_extension/mini_racer_extension.c
- ext/mini_racer_extension/mini_racer_v8.cc
- test/mini_racer_test.rb
Use of ser_array_begin in two cases caused an off-by-one error in the object back-reference count that is used to stop an object from being encoded more than once (and thus maintains object identity, allowing recursive structures.)
> Fix object serialization

- README.md
- ext/mini_racer_extension/extconf.rb
- ext/mini_racer_extension/mini_racer_extension.c
- ext/mini_racer_extension/mini_racer_v8.cc
- ext/mini_racer_extension/mini_racer_v8.h
- lib/mini_racer/truffleruby.rb
- lib/mini_racer/version.rb
- test/mini_racer_test.rb
Removes context.idle_notification because the V8 API it uses has been removed with no real replacement.
V8 suggests to use Isolate::MemoryPressureNotification() instead but that's not really the same thing and overlaps significantly with context.low_memory_notification.
Remove the stale object marshalling section from the README.
<hr>
Needs a libv8-node release from its node-23 branch first
> Update to V8 12.9

- ext/mini_racer_extension/mini_racer_v8.cc
- test/mini_racer_test.rb
Don't abort when the ruby thread calls `context.stop` right when the V8 thread is serializing its response to a request. Temporarily cancel the termination exception, retry serialization, and reraise the exception.
> Handle termination exceptions during serialization

- ext/mini_racer_extension/mini_racer_extension.c
- ext/mini_racer_extension/serde.c
- test/mini_racer_test.rb
Numbers outside the range that double-precision floating-point numbers can represent exactly are now converted to JS BigInts instead of being rejected outright. Said range corresponds to `Number.MIN_SAFE_INTEGER` and `Number.MAX_SAFE_INTEGER` on the JS side.
Refs: https://github.com/rubyjs/mini_racer/issues/348
> Convert big ruby integers to js bigints

- test/mini_racer_test.rb
Fixes: https://github.com/rubyjs/mini_racer/issues/351
> Handle missing timezone data in test

- .github/workflows/ci.yml
GitHub discontinued support for `ubuntu-20.04` in April (see https://github.com/actions/runner-images/issues/11101), that's why the `test-truffleruby` job currently fails.
> CI: Use ubuntu-24.04 for test-truffleruby

- .github/workflows/ci.yml
- Rakefile
I saw @bnoordhuis's change in https://github.com/rubyjs/mini_racer/pull/352.
I think instead of swallowing the error because it breaks in CI, we should fix the CI setup. I suspect that the TZInfo zoneinfo data is simply missing in the Ruby alpine docker image.
I tested this with docker and `ruby:3.4-alpine`. When I install the required tzdata (via `apk add --no-cache tzdata`) it works as expected:
```
irb(main):001> require "active_support"
=> true
irb(main):002> require "active_support/time"
=> true
irb(main):003> Time.zone = "UTC"
=> "UTC"
```
Without the `tzdata`package, it breaks like described in https://github.com/rubyjs/mini_racer/issues/351.
> CI: Install tzdata for musl-based Ruby docker images

- ext/mini_racer_extension/mini_racer_extension.c
- test/test_object_identity_fix.rb
> [!WARNING]
> C is not my area of expertise. Vibe code content warning 😅 - please review as such! Thank you!
This fixes a bug where separate Ruby objects with identical content were incorrectly sharing the same JavaScript object reference during serialization.
Problem:
- Ruby hashes like `[{"value" => 42}, {"value" => 42}, {"value" => 42}]` were becoming the same JavaScript object reference
- Mutating one object affected all identical objects
- This happened because serialization used Ruby's content-based hash equality instead of object identity for reference tracking
Solution:
- Modified `serialize1()` in `mini_racer_extension.c` to use `rb_obj_id(v)` as the hash key instead of the object itself (v)
- This ensures only truly identical Ruby objects (same memory address) share JavaScript …
> Fix object identity bug in Ruby-to-JavaScript conversion
